apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: satellite-dr
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: kwakousteve/satdr_be
        name: satdrbe
        envFrom:
        - secretRef:
            name: satellite-dr-secrets
