apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: satellite-dr
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: kwakousteve/satdr_fe_cli
        name: satdrfecli
